### ISSUE TITLE
TypeError: 'Elasticsearch' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by nakagit** [upgoingstar/TwitterBot#1]
Traceback (most recent call last):
  File "./tweetmonitor.py", line 95, in <module>
    search(options.keyword)
  File "./tweetmonitor.py", line 71, in search
    stream.filter(track=[xyz])
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 450, in filter
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 364, in _start
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 297, in _run
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 266, in _run
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 327, in _read_loop
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 300, in _data
  File "./tweetmonitor.py", line 59, in on_data
    dumpToElastic(list_data, ip, port)
  File "./tweetmonitor.py", line 90, in dumpToElastic
    print(es['created'])
TypeError: 'Elasticsearch' object has no attribute '__getitem__'

<Environment>
Ubuntu 16.04 (64bit)
Elasticsearch 5.3.1
Tweepy 3.6.0

Please let me know the informations you need to debug.

Thanks in advance,
YN

**Comment by nakagit** [comment]
I'd like to broadcast your great and wonderful tool through SNS(FB and Twitter).

I hope you'll reply me back and I'm willing to help your debug.

Warm regards,
YN

**Comment by nakagit** [comment]
When I used Python 2.7, above error occurred.  Then, when I used Python 3.x, TweetMonitor worked fine.
So, let me close this issue.

Sorry, I bother you.

This TweetMonitor is a wonderful tool/script.   :)

Kindest regards,
YN
